feat: change component file name

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -50,8 +50,8 @@ jobs:
             - run: edgee component build
             - name: Verify .wasm file exists
               run: |
-                  if [ ! -f "./example-js-component.wasm" ]; then
-                      echo "❌ Error: example-js-component.wasm not found" >&2
+                  if [ ! -f "./dc_component.wasm" ]; then
+                      echo "❌ Error: dc_component.wasm not found" >&2
                       exit 1
                   fi
 
